"""add_additional_control_field

Revision ID: 0b54ce5afb9c
Revises: 346059db34db
Create Date: 2025-06-16 02:28:02.889318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b54ce5afb9c"
down_revision: Union[str, None] = "346059db34db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_settings", sa.Column("additional_control", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE admin_settings SET additional_control = 150")
    op.alter_column("admin_settings", "additional_control", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_settings", "additional_control")
    # ### end Alembic commands ###
