"""remove_package

Revision ID: 284e10fe3db1
Revises: ce87b8259d57
Create Date: 2025-06-20 01:09:36.353011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "284e10fe3db1"
down_revision: Union[str, None] = "ce87b8259d57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "packaging")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("packaging", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
