"""fill_admin_settings

Revision ID: 346059db34db
Revises: caac4355fa12
Create Date: 2025-06-15 14:11:11.843562

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "346059db34db"
down_revision: Union[str, None] = "caac4355fa12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO admin_settings (commision_rate, kilo_delivery, cny_rate_syrcharge, user_tg_id)
        VALUES (0.1, 2300, 0.85, 1)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM admin_settings
        WHERE user_tg_id = 1
        """
    )
    # ### end Alembic commands ###
