"""insert_admin_settings

Revision ID: 7327aab6514f
Revises: 39cf7ffd05ec
Create Date: 2025-06-18 23:46:30.006387

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7327aab6514f"
down_revision: Union[str, None] = "39cf7ffd05ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO admin_settings (commision_rate, kilo_delivery, cny_rate_syrcharge, user_tg_id, additional_control)
        VALUES (0.1, 2300, 0.85, 1, 200)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM admin_settings
        WHERE user_tg_id = 1
        """
    )
    # ### end Alembic commands ###
