"""update_address_table

Revision ID: 840de0506ec7
Revises: d197f98f5d30
Create Date: 2025-06-17 02:16:54.724818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "840de0506ec7"
down_revision: Union[str, None] = "d197f98f5d30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("addresses", sa.Column("city", sa.String(), nullable=False))
    op.add_column("addresses", sa.Column("index", sa.Integer(), nullable=False))
    op.add_column("addresses", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("addresses", "name")
    op.drop_column("addresses", "index")
    op.drop_column("addresses", "city")
    # ### end Alembic commands ###
