"""start_fill

Revision ID: 955d1d0dae76
Revises: f56bedabe72f
Create Date: 2025-07-11 19:58:19.672161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "955d1d0dae76"
down_revision: Union[str, None] = "f56bedabe72f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
