"""add_faq_field

Revision ID: c6ec243ca4ec
Revises: 7327aab6514f
Create Date: 2025-06-19 00:27:59.853185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6ec243ca4ec"
down_revision: Union[str, None] = "7327aab6514f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admin_settings", sa.Column("faq", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_settings", "faq")
    # ### end Alembic commands ###
