"""price_per_unit

Revision ID: c99f74ba88ca
Revises: 284e10fe3db1
Create Date: 2025-06-26 01:52:21.039265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c99f74ba88ca"
down_revision: Union[str, None] = "284e10fe3db1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "unit_price_rmb", sa.Float(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "unit_price_rub", sa.Float(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.drop_column("orders", "unit_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "unit_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("orders", "unit_price_rub")
    op.drop_column("orders", "unit_price_rmb")
    # ### end Alembic commands ###
