"""add_decimal

Revision ID: f56bedabe72f
Revises: c99f74ba88ca
Create Date: 2025-06-26 02:13:48.946559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f56bedabe72f"
down_revision: Union[str, None] = "c99f74ba88ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "unit_price_rmb",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=18, scale=2),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "orders",
        "unit_price_rub",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=18, scale=2),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "orders",
        "final_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=18, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "final_price",
        existing_type=sa.DECIMAL(precision=18, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "unit_price_rub",
        existing_type=sa.DECIMAL(precision=18, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "orders",
        "unit_price_rmb",
        existing_type=sa.DECIMAL(precision=18, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
